# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuegoCli < Formula
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.4.0/fuego_0.4.0_darwin_amd64.tar.gz"
      sha256 "2f52e84884fea0ceacfdf31683d58c2ea965f936b9018a408297b1b52b390077"

      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.4.0/fuego_0.4.0_darwin_arm64.tar.gz"
      sha256 "96a7dfcf2c0e2c6dbfa64f819e88450b2e42757da440d192ce8a1bac556c6e82"

      def install
        bin.install "fuego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.4.0/fuego_0.4.0_linux_amd64.tar.gz"
      sha256 "0e7ea65edf5c35028357a89d24786f8283ffc388f8022bdb6f59f776430d6a1c"
      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.4.0/fuego_0.4.0_linux_arm64.tar.gz"
      sha256 "b053621cc09d811f208feaf5e9d6ad679345a6cf515f0b4b815ae838f0dd9608"
      def install
        bin.install "fuego"
      end
    end
  end
end
