# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuegoCli < Formula
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.4/fuego_0.3.4_darwin_amd64.tar.gz"
      sha256 "0449e477bfb1960920aa965457e15e1d4b42e8b7c72c0599e670db971446343e"

      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.4/fuego_0.3.4_darwin_arm64.tar.gz"
      sha256 "57af6d14e6e5cf445fe45b2ac7291bb317ecf8d51a243319d7169864aea27a2c"

      def install
        bin.install "fuego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.4/fuego_0.3.4_linux_amd64.tar.gz"
      sha256 "d949cea4a55f789760c7f588d30f55944ffe1b632f405111879b2d569e76a0f8"
      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.4/fuego_0.3.4_linux_arm64.tar.gz"
      sha256 "cf9a47d60b36932678e9b425ef013bf1761d36449450875e0bbc92111527ea6a"
      def install
        bin.install "fuego"
      end
    end
  end
end
