# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuego" do
  name "fuego"
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuego"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_amd64.tar.gz"
      sha256 "b6334a8062214cced7680bd9cd6fb3f61be1ea85ff22bd3a606ca611dab13160"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_arm64.tar.gz"
      sha256 "76078baa9621fd4641454f80bda3510d1124610474bdc31aa9947e3431045755"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_amd64.tar.gz"
      sha256 "ec7feeba7c5df2048115c0a945b231501309f2fb2df320ceefe19e55696d4a5d"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_arm64.tar.gz"
      sha256 "30e8f55c21fc716bff2ac1b5a682d372efd620cfbfbdc429f3428847d30e9e4e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuego"]
    end
  end

  # No zap stanza required
end
