# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuego-cli" do
  name "fuego-cli"
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.9.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuego"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_amd64.tar.gz"
      sha256 "984454d52842f15303c77ffb7b85034d997008a39900a118926897f95c42cf68"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_arm64.tar.gz"
      sha256 "3b5e0564b1b59172271ce5331391d3ab733a82941ec41b604d50907140800a1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_amd64.tar.gz"
      sha256 "343f3b2e28b06d9a07ff076046ed8c3a766eccc9c3fe63ebc762c69ae66d8997"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_arm64.tar.gz"
      sha256 "f93c11cd9cecf7df85bb7f1657633c210de7acb17da7416d3948a41f292ea8bd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuego"]
    end
  end

  # No zap stanza required
end
