# This file was generated by GoReleaser. DO NOT EDIT.
cask "nexo-cli" do
  name "nexo-cli"
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/nexo"
  version "0.11.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nexo"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_darwin_amd64.tar.gz"
      sha256 "4134e6c3e1a2274ff3365c22692c6223b8608c62ea05e0b790d68c7b6a6e3418"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_darwin_arm64.tar.gz"
      sha256 "d91be2b6cd26ab2ed8f680fd05b2160ea376cb55fb4c28b8bd49f3c73dc4bef5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_linux_amd64.tar.gz"
      sha256 "4deae5476fcd20017d2108acd693c635992777c866eb4baa994becc42292261e"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_linux_arm64.tar.gz"
      sha256 "50dd5c2b1e3d104e3c0f025915facc533f8f1383ff56acb6246923c1c1c6821e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nexo"]
    end
  end

  # No zap stanza required
end
