# This file was generated by GoReleaser. DO NOT EDIT.
cask "nexo-cli" do
  name "nexo-cli"
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/nexo"
  version "0.11.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nexo"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_darwin_amd64.tar.gz"
      sha256 "d46e794e741a5ad73c1d1be452f731a888ac9c69c9829505422c23634697e58f"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_darwin_arm64.tar.gz"
      sha256 "6bc66a9bad970f3f80642a89b4e94213e7d010bf5aa1b815120f5e075a4afa99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_linux_amd64.tar.gz"
      sha256 "78d58f2eb92d83fc2c7ed6e0ac646013d1bf22ed38c1a2d9a1daac33d4ce1c27"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_linux_arm64.tar.gz"
      sha256 "7569b7cdede3a02c4b19f735a72e0e9e37e96922a838bebb9574ab9e6ad642c5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nexo"]
    end
  end

  # No zap stanza required
end
