# This file was generated by GoReleaser. DO NOT EDIT.
cask "nexo-cli" do
  name "nexo-cli"
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/nexo"
  version "0.11.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nexo"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_darwin_amd64.tar.gz"
      sha256 "32b97381d9981a46f4434bf2578937e00aa0b8e4f57015feafb1cec420de0d7e"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_darwin_arm64.tar.gz"
      sha256 "d20a108beb8e0e98dade58a4e8695c23c3e546c0e03edd546d72745e86640c3b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_linux_amd64.tar.gz"
      sha256 "08481f81667f7f38da209e06c3a73208b2eb7cc261fce2915f0de4fa85f3d8ce"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/nexo/releases/download/v#{version}/nexo_#{version}_linux_arm64.tar.gz"
      sha256 "ee44f3da5203ee7fa8f89b3ee6a60261dccf7c085d8463d58683e6c26fa75361"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nexo"]
    end
  end

  # No zap stanza required
end
